name: Test

on:
  push:
    branches: [yaml_test_branch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Run unit tests
        run: python -m unittest testFile.py
